### ISSUE TITLE
equation (9)

### ISSUE THREAD

**Issue by ghost** [mongeoroo/Relevance-CAM#2]
![图片](https://user-images.githubusercontent.com/41811026/138406083-84014c30-93e1-4e59-a4fe-d8d691d68d45.png)
Thank you for your excellent work. I would like to ask about the meaning of x and y in equation (9). I did not see your explanation in the paper.

**Comment by mongeoroo** [comment]
Thank you for your attention.

The x,y means the regional position of the feature map. And that equation is for global pooling layer.

For example, if Relevance map(R) has shape of (batch, channel, height, width),

alpha has shape of (batch, channel, 1, 1).

Therefore, that alpha can be interpreted as the contribution of each feature map to target class logit.

**Comment by ghost** [comment]
Thank you for your reply, which is very detailed.
