### ISSUE TITLE
vgg19

### ISSUE THREAD

**Issue by Yung-zi** [mongeoroo/Relevance-CAM#4]
Thanks for you great job! However, I have a question. When I use vgg19 rather than vgg16, there is an error shown below. It seems that something is wrong, the code path of which is "./modules/layers.py". Can it be used in vgg19 or we need to do some change to make it in vgg19. By the way, can it be used with transformer network? I am looking forward to your reply! 

RuntimeError: The size of tensor a (7) must match the size of tensor b (14) at non-singleton dimension 3

**Comment by mongeoroo** [comment]
Thanks, I upload my code, and  it will work in vgg19.

And also update readme commend line about vgg19
