### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1) when training my custom dataset with resnet50 with its layer 1

### ISSUE THREAD

**Issue by may-phyu** [mongeoroo/Relevance-CAM#7]
I do thank you so much to get your paper with github code because it helps me a lot to my study. It is ok to train with my custom dataset with other layers (2, 3 and 4) but not its layer 1. Please help me how I should fix it.

**Comment by britney-code** [comment]
> I do thank you so much to get your paper with github code because it helps me a lot to my study. It is ok to train with my custom dataset with other layers (2, 3 and 4) but not its layer 1. Please help me how I should fix it.

you should add some code，example layer1，` elif mode == 'layer1':
            R3 = self.layer4.relprop(R4, 1)
            R2 = self.layer3.relprop(R3, 1)
            R1 = self.layer2.relprop(R2, 1)
            r_weight1 = torch.mean(R1, dim=(2, 3), keepdim=True)
            r_cam1 = layer1 * r_weight1
            r_cam1 = torch.sum(r_cam1, dim=(1), keepdim=True)
            return r_cam1,z`
